#spring:
#  application:
#    name: advertisement-api
##  cloud:
##    config:
##       uri: http://localhost:8070
##       failFast: true
#
#server:
#  port: 8090
##
#spring:
#  application:
#    name: advertisement-api
#server:
#  port: 0
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true